require: rubocop-rails
# Modify the version if you don't use MRI 2.1.
AllCops:
  TargetRubyVersion: 2.5
  # If you use RuboCop with Ruby on Rails, specify TargetRailsVersion(default: 5.0).
  TargetRailsVersion: 5.0
  Exclude:
    - db/schema.rb
    - db/seeds.rb
    - bin/*
    - vendor/**/*
    - db/migrate/*
    - 'config/deploy.rb'
    - 'config/deploy/**/*'

Rails:
  # If you use RuboCop with Ruby on Rails, turn on this option.
  Enabled: true
Style/FrozenStringLiteralComment:
  Enabled: false